@startuml datatypes
title Complex DataTypes

abstract class Organization {
    Legal entity
    -----
    name : String[1..1]
    address : String[0..*]
}

abstract class Location {
    physical location
    -----
    country : String[1..1] - Should be ISO 3166-1
    state : String[0..1] - Should be 3166-2
}
abstract class Period {
    period of date/time
    -----
    start : DateTime[0..1]
    end : DateTIme[0..1]
}
abstract class Concept {
    Coded concept 
    ----
    code : String[0..1]
    system : URI[0..1]
    description : String[0..1]
}

abstract class Classification {
    Sensitivity Classifications
    -----
    regulation : Concept[1..1]
    evaluated : boolean[1..1]
    tool : String[0..1]
}

abstract class PrivacyEnhancing {
    Indicate the privacy tools used and results obtained
    -----
    tool-category : Concept[1..1] - from Privacy Enhancing Tools
    tool-used : String[0..1]
    parameters : String[0..*]
    result : String[0..*]
}
@enduml