@startuml metadata
title Data Provenance

entity Data

abstract class Metadata {
    source : Source[1..1]
    provenance : Provenance[1..1]
    use : Use[1..1]
}

Metadata *-down- Source 
Metadata *-down- Provenance 
Metadata *-down- Use 
Metadata -left-> Data

abstract class Source {
    Identifies the dataset and source of the dataset
    ----
    version : String[1..1]
    title: String[1..1]
    id : URI[1..1]
    location : URL[0..1]
    issuer : Organization[1..*]
    description : String[1..1]
}

abstract class Provenance {
    The provenance of the dataset
    -----
    source : URL[0..1]
    origin : Organization[0..1]
    date : DateTime[1..]
    previous-date : DateTime[0..1]
    generation-period : Period[0..1]
    generation-method : Concept[1..*]
    format : String[0..*]
    sub-provenance : Provenance[0..*]
}

Provenance *-down- Provenance

abstract class Use {
    Legal, Use, and Restrictions
    ------
    classification : Classification[1..1]
    consents : URL[0..*]
    privacy-enhancing : PrivacyEnhancing[0..*]
    processing-included : Location[0..*]
    processing-excluded : Location[0..*]
    storage-allowed : Location[0..*]
    storage-forbidden : Location[0..*]
    license : String[0..1]
    intended-purpose : Concept[1..*]
    copyright : String[0..*]
    patent : String[0..*]
    trademark : String[0..*]
}


@enduml